# Generated by Django 4.0.5 on 2022-06-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='allergies_info',
            field=models.JSONField(blank=True, default=dict, encoder=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='diseases_info',
            field=models.JSONField(blank=True, default=dict, encoder=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, encoder=''),
        ),
    ]
