# Generated by Django 4.0.5 on 2022-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_allergies_info_alter_pet_diseases_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='allergies_info',
            field=models.JSONField(blank=True, default=dict, encoder='', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='diseases_info',
            field=models.JSONField(blank=True, default=dict, encoder='', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pets'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
