# Generated by Django 4.0.5 on 2022-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_allergies_info_alter_pet_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, encoder='', null=True),
        ),
    ]
